import { create } from "zustand";

const initialState = {
  ContestLogs: [],
  allowReceiveNotificationInfo: [],
  birthdate: null,
  blog_url: null,
  bookMarkPhotoList: [],
  bookMarkVideoList: [],
  career: null,
  count_follower: 1,
  count_like: 0,
  country: 1,
  created_at: null,
  cumulative_receive_push: 0,
  cumulative_send_push: 0,
  email: null,
  facebook_url: null,
  followingList: [],
  gender: null,
  google_email: null,
  google_id: null,
  hasSimplePassword: null,
  have_push: 0,
  instagram_url: null,
  introduce: null,
  is_dnd_mode: null,
  is_dreamer: null,
  is_init_allow_receive_noti: null,
  is_producer: null,
  isLoggedIn: false,
  job: null,
  jumin_id: null,
  kakao_id: null,
  likeCommentList: [],
  likeReplyList: [],
  likeUserList: [],
  likeVideoList: [],
  local_id: null,
  name_verified: null,
  naver_id: null,
  newMessageCheckLog: {
    notice: [],
    notification: [],
    vote: [],
  },
  nickname: null,
  pin_vote_image: null,
  receive_push: 0,
  reportInfo: {
    videoList: [],
    photoList: [],
    commentList: [],
  },
  royalty: 0,
  speciality: null,
  terms_apply_time: null,
  twitter_url: null,
  user_name: null,
  user_no: null,
  user_photo: null,
  user_type: null,
  verified_account_time: null,
  verified_name_time: null,
  verify_birthdate: null,
  verify_bnk_cd: null,
  verify_name: null,
  withdrawal_account: null,
  withdrawal_account_verified: 0,
  withdrawal_bank: null,
  youtube_url: null,
};

const useUserStore = create((set) => ({
  ...initialState,
  login: (user) => set(user),
  logout: () => set(initialState),
}));

export default useUserStore;
